version: "2"
services:
  subscription-frontend:
    image: subscription-frontend
    ports:
      - "3000:80"
  subscription-gateway:
    image: subscription-gateway
    ports:
      - "8087:8080"
    environment:
      SUBSCRIPTION_SERVICE_URL: http://subscription-service:8080
      REGISTRATION_SERVICE_URL: http://registration-service:8080
    depends_on:
      - "kafka"
      - "db"
      - "registration-service"
      - "subscription-service"
  subscription-service:
    image: subscription-service
    ports:
      - "8086:8080"
    environment:
      DB_ADDR: db
      DB_PORT: 5432
      DB_NAME: subscription-service-db
      DB_USERNAME: admin
      DB_PASSWORD: adminadmin
      KAFKA_ADDR: kafka
      KAFKA_PORT: 29092
    depends_on:
      - "kafka"
      - "db"
      - "registration-service"
  registration-service:
    image: registration-service
    ports:
      - "8085:8080"
    environment:
      DB_ADDR: db
      DB_PORT: 5432
      DB_NAME: registration-service-db
      DB_USERNAME: admin
      DB_PASSWORD: adminadmin
      KAFKA_ADDR: kafka
      KAFKA_PORT: 29092
    depends_on:
      - "kafka"
      - "db"
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
  db:
    image: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"