logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: get-services
          uri: ${REGISTRATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/services
            - Method=GET
        - id: add-event-subscription
          uri: ${SUBSCRIPTION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/event-subs
            - Method=POST
        - id: del-event-subscription
          uri: ${SUBSCRIPTION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/event-subs
            - Method=DELETE
            - Query=service-name
            - Query=event-name